name: Laravel Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'testing'
        type: choice
        options:
          - testing
          - staging
          - production

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: xdebug

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Composer dependencies
      run: |
        composer config --no-plugins allow-plugins.pestphp/pest-plugin true
        composer config --no-plugins allow-plugins.php-http/discovery true
        composer install --prefer-dist --no-interaction --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Clear composer cache
      run: composer clear-cache

    - name: Execute tests with coverage
      env:
        MOCKERY_CLOSE_ON_DESTRUCT: true
        PHP_MEMORY_LIMIT: 2G
      run: |
        vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 